scripts:
  - name: Test App Server
    command: |
      uv run tests/manage.py runserver "localhost:$(python3 -c "import socket; s=socket.socket(); s.bind(('127.0.0.1',0)); print(s.getsockname()[1]); s.close()")"
    triggers:
      - session.create
auto_open_in_browser: true
automation:
  auto_issue_session: true
