repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-ast
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ["--pytest-test-first"]
        exclude: ^tests/(testapp/|manage\.py)
      - id: no-commit-to-branch
        args: [--branch, main]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py312-plus]
  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.33.0
    hooks:
      - id: django-upgrade
  - repo: https://github.com/UnknownPlatypus/djangofmt-pre-commit
    rev: v1.0.0
    hooks:
      - id: djangofmt
  - repo: https://github.com/hukkin/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-config
          - mdformat-beautysh
          - mdformat-footnote
          - mdformat-gfm
          - mdformat-gfm-alerts
          - mdformat-ruff
          - mdformat-web
          - mdformat-frontmatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.10
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.30.1
    hooks:
      - id: pyproject-fmt
  - repo: https://github.com/google/yamlfmt
    rev: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/codingjoe/esupgrade
    rev: 2026.1.0
    hooks:
      - id: esupgrade
        exclude: ^django_letter/static/django_letter/[\w.-]+\.min\.js$
  - repo: https://github.com/oxc-project/mirrors-oxlint
    rev: v1.60.0
    hooks:
      - id: oxlint
        exclude: ^django_letter/static/django_letter/[\w.-]+\.min\.js$
  - repo: https://github.com/oxc-project/mirrors-oxfmt
    rev: v0.71.0
    hooks:
      - id: oxfmt
        exclude: ^django_letter/static/django_letter/[\w.-]+\.min\.js$
  - repo: local
    hooks:
      - id: svgo
        name: svgo
        language: node
        additional_dependencies: [svgo]
        entry: svgo
        args: [--pretty, --multipass, --indent, "2"]
        require_serial: true
        pass_filenames: true
        types: [svg]
ci:
  autoupdate_schedule: weekly
  skip:
    - no-commit-to-branch
